site_name: My Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
theme:
  name: material

  include_search_page: false
  search_index_only: true

  palette:
    - scheme: slate
      primary: red
      accent: orange
  
  highlightjs: true
  hljs_languages:
    - yaml
    - rust